config/routes.rb
Rails.application.routes.draw do
  root to: 'artists#index'
  resources :artists
  resources :artworks



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :artworks
  validates :name, presence: true, uniqueness: true

end

app/models/artwork.rb
class Artwork < ApplicationRecord
  belongs_to :artist
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :destroy]
  def index
    @artists = Artist.all
  end

  def show
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.create(artist_params)
    if @artist.valid?
      redirect_to @artist
    else
      render 'new'
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  private

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name, :birthyear, :deathyear)
  end

end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :set_artist, only: [:show, :destroy]

  def index
    @artworks = Artwork.all
  end

  def show
    @artwork = Artwork.find(params[:id])
  end

  def new
    @artwork = Artwork.new
  end

  def create
    @artist = Artist.find(params[:artwork][:artist_id])
    @artwork = @artist.artworks.create!(artwork_params)
    if @artwork.valid?
      redirect_to @artwork
    else
      redirect_to new_artwork_path
    end
  end

  def destroy
    @artwork = Artwork.find(params[:id])
    @artwork.destroy
    redirect_to @artist
  end

  private

  def artwork_params
    params.require(:artwork).permit(:name, :artist_id, :year, :image_url)
  end

  def set_artist
    @artist = Artwork.find(params[:id]).artist
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/views/artists/index.html.erb
<div id="my-gallery-logo"><%= image_tag "myGalleryLogoSmall.png" %></div>
<h1 class="welcome-page-header">My Gallery</h1>

<table>
  <thead>
    <tr>
      <th>Artist name</th>
      <th colspan="3"></th>
      </tr>
  </thead>

  <tbody>
  <% @artists.each do |artist| %>
    <tr>
      <td><%= artist.name %></td>
      <td><%= link_to 'Profile page', artist %></td>
    <td><%= link_to 'Delete', artist, method: :delete, data: { confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
  </table>


<br>

<div class="footer-links">
  <h4><%= link_to 'Add an artist', new_artist_path %></h4>
  <h4><%= link_to 'Add an artwork', new_artwork_path %></h4>
  <h4><%= link_to 'All artworks in the gallery', artworks_path %></h4>
</div>

app/views/artists/new.html.erb
<h1>Add an Artist</h1>
<br>
<%= form_for @artist do |f| %>
<div class="field">
  <p class="label-details"><%= f.label :name %></p>
  <%= f.text_field :name, :size => 40 %>
  </div>
  <br>
  <div class="field">
    <p class="label-details"><%= f.label :birthyear, "Year of birth" %></p>
    <%= f.number_field :birthyear, :size => 20, min: 1850, max: 2019 %>
    </div>
    <br>
    <div class="field">
    <p class="label-details"><%= f.label :deathyear, "Year of death (leave blank for living artists)" %></p>
      <%= f.number_field :deathyear, :size => 20, min: 1870, max: 2019, :value => "" %>
      </div>
      <br>
  <div class="action">
  <%= f.submit "Submit" %>
  </div>
<% end %>

<div id="new-form-home-link" class="footer-links">
<h4><%= link_to 'Home', artists_path %></h4>
</div>

app/views/artists/show.html.erb
<h1 class="header"><%= @artist.name %></h1>

<% if @artist.deathyear != nil
    @lifespan = "(" + @artist.birthyear.to_s + " - " + @artist.deathyear.to_s + ")"
  else
    @lifespan = "(" + @artist.birthyear.to_s + " - )"
  end %>
<h3 id="lifespan"><%= @lifespan %></h3>

<h4 class="quantity"><%= pluralize(@artist.artworks.count, 'artwork') %></h4>
<ul>
  <% @artist.artworks.each do |artwork| %>
    <li className="artwork-link"><%= link_to artwork.name, artwork_path(artwork) %></li>
  <% end %>
</ul>

<br>
<div class="footer-links">
  <h4><%= link_to 'Back', artists_path %></h4>
  <h4><%= link_to 'Add an Artwork', new_artwork_path %></h4>
</div>

app/views/artworks/index.html.erb
<h1>All artworks in the gallery</h1>

<table>
  <thead>
    <tr>
      <th>Artwork name</th>
      <th colspan="3"></th>
      </tr>
  </thead>

  <tbody>
  <% @artworks.each do |artwork| %>
    <tr>
      <td><%= artwork.name %></td>
      <td><%= link_to 'About', artwork %></td>
    <td><%= link_to 'Delete', artwork, method: :delete, data: { confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
  </table>


<br>

<h3 className="footer-links"><%= link_to 'Add an Artist', new_artist_path %></h3>
<h3 className="footer-links"><%= link_to 'Add an Artwork', new_artwork_path %></h3>
<h3 className="footer-links"><%= link_to 'Home', artists_path %></h3>
<br>

app/views/artworks/new.html.erb
<h1>Add an Artwork</h1>
<br>
<%= form_for [@artist, @artwork] do |f| %>
  <div class="field">
  <p class="label-details"> <%= f.label :name, "Name:" %></p>
  <%= f.text_field :name, :size => 50 %>
  </div>
  <br />
  <div class="field">
  <p class="label-details"><%= f.label :year, "Year:" %></p>
  <%= f.number_field :year, :size => 15, min: 1850, max: 2019 %>
  </div>
  <br>
  <p class="label-details"><%= f.label :artist_id, "Artist:" %></p>
  <%= f.collection_select :artist_id, Artist.all, :id, :name %>
  <br>
  <br>
  <div class="field">
  <p class="label-details"><%= f.label :image_url, "Add a link to an image of the artwork"%></p>
  <%= f.text_field :image_url, :size => "90%" %>
  <div class="actions">
  <br>
  <%= f.submit %>
  </div>
<% end %>


<div class="footer-links">
<h4><%= link_to "Add an artist", new_artist_path %></h4>
<h4><%= link_to 'Home', artists_path %></h4>
</div>

app/views/artworks/show.html.erb
<div id="artwork-page">
<div class="artwork-bio">
  <h2><%= @artwork.name %></h2>
  <h4><%= @artwork.year %></h4>
  <h3>By: <%= link_to @artwork.artist.name, artist_path(@artwork.artist) %></h3>
</div>
<br>

<img class="artwork-image" src=<%= @artwork.image_url%> alt=<%= @artwork.name %> />
<br>
<br>
<div class="footer-links">
  <h4><%= link_to "Delete this artwork from the gallery", @artwork, method: :delete, data: {confirm: 'Are you sure?'} %></h4>
  <h4><%= link_to "Back to all " + @artwork.artist.name , artist_path(@artwork.artist) %></h4>
  <h4><%= link_to 'Home', artists_path %></h4>
</div>
<br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gallery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
  <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,600,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
    <div class="wrapper">
      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">The Gallery app</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><a href="/artists/new">Add an Artist</a></li>
          <li><a href="/artworks/new">Add an Artwork</a></li>
        </ul>
      </div>
    </div>
  </nav>
    <div class="container">
    <%= yield %>
  </div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script>
  </body>

  <footer class="footer">
  <div class="container">
    <span class="text-muted">The Gallery <%= Time.now.year %></span>
  </div>
  </footer>
</html>